// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/task/task.proto

package task

import (
	context "context"
	fmt "fmt"
	math "math"

	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type TaskRequest struct {
	Request              string   `protobuf:"bytes,1,opt,name=request,proto3" json:"request,omitempty"`
	NameReq              string   `protobuf:"bytes,2,opt,name=nameReq,proto3" json:"nameReq,omitempty"`
	AgeReq               int32    `protobuf:"varint,3,opt,name=ageReq,proto3" json:"ageReq,omitempty"`
	LocalTime            string   `protobuf:"bytes,4,opt,name=localTime,proto3" json:"localTime,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TaskRequest) Reset()         { *m = TaskRequest{} }
func (m *TaskRequest) String() string { return proto.CompactTextString(m) }
func (*TaskRequest) ProtoMessage()    {}
func (*TaskRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_152e577c5c92a6d4, []int{0}
}

func (m *TaskRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TaskRequest.Unmarshal(m, b)
}
func (m *TaskRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TaskRequest.Marshal(b, m, deterministic)
}
func (m *TaskRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TaskRequest.Merge(m, src)
}
func (m *TaskRequest) XXX_Size() int {
	return xxx_messageInfo_TaskRequest.Size(m)
}
func (m *TaskRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_TaskRequest.DiscardUnknown(m)
}

var xxx_messageInfo_TaskRequest proto.InternalMessageInfo

func (m *TaskRequest) GetRequest() string {
	if m != nil {
		return m.Request
	}
	return ""
}

func (m *TaskRequest) GetNameReq() string {
	if m != nil {
		return m.NameReq
	}
	return ""
}

func (m *TaskRequest) GetAgeReq() int32 {
	if m != nil {
		return m.AgeReq
	}
	return 0
}

func (m *TaskRequest) GetLocalTime() string {
	if m != nil {
		return m.LocalTime
	}
	return ""
}

type TaskResponse struct {
	Response             string   `protobuf:"bytes,1,opt,name=response,proto3" json:"response,omitempty"`
	NameRes              string   `protobuf:"bytes,2,opt,name=nameRes,proto3" json:"nameRes,omitempty"`
	AgeRes               int32    `protobuf:"varint,3,opt,name=ageRes,proto3" json:"ageRes,omitempty"`
	LocalAndServerTime   string   `protobuf:"bytes,4,opt,name=localAndServerTime,proto3" json:"localAndServerTime,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TaskResponse) Reset()         { *m = TaskResponse{} }
func (m *TaskResponse) String() string { return proto.CompactTextString(m) }
func (*TaskResponse) ProtoMessage()    {}
func (*TaskResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_152e577c5c92a6d4, []int{1}
}

func (m *TaskResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TaskResponse.Unmarshal(m, b)
}
func (m *TaskResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TaskResponse.Marshal(b, m, deterministic)
}
func (m *TaskResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TaskResponse.Merge(m, src)
}
func (m *TaskResponse) XXX_Size() int {
	return xxx_messageInfo_TaskResponse.Size(m)
}
func (m *TaskResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_TaskResponse.DiscardUnknown(m)
}

var xxx_messageInfo_TaskResponse proto.InternalMessageInfo

func (m *TaskResponse) GetResponse() string {
	if m != nil {
		return m.Response
	}
	return ""
}

func (m *TaskResponse) GetNameRes() string {
	if m != nil {
		return m.NameRes
	}
	return ""
}

func (m *TaskResponse) GetAgeRes() int32 {
	if m != nil {
		return m.AgeRes
	}
	return 0
}

func (m *TaskResponse) GetLocalAndServerTime() string {
	if m != nil {
		return m.LocalAndServerTime
	}
	return ""
}

func init() {
	proto.RegisterType((*TaskRequest)(nil), "task.TaskRequest")
	proto.RegisterType((*TaskResponse)(nil), "task.TaskResponse")
}

func init() { proto.RegisterFile("proto/task/task.proto", fileDescriptor_152e577c5c92a6d4) }

var fileDescriptor_152e577c5c92a6d4 = []byte{
	// 218 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x90, 0x4b, 0x4a, 0xc5, 0x30,
	0x14, 0x86, 0x8d, 0x5e, 0xab, 0xf7, 0xe8, 0xc4, 0x03, 0x4a, 0xb8, 0x38, 0x28, 0x1d, 0x75, 0x54,
	0x51, 0x37, 0xa0, 0x5b, 0x48, 0xbb, 0x81, 0x58, 0x0f, 0x5a, 0xfa, 0x48, 0x9b, 0x53, 0x75, 0x13,
	0x2e, 0x5a, 0x9a, 0xc4, 0x3e, 0xe0, 0x4e, 0xc2, 0xff, 0x20, 0x7c, 0x87, 0x1f, 0x6e, 0x7b, 0x6b,
	0x46, 0xf3, 0x30, 0x6a, 0xae, 0xdd, 0x93, 0x39, 0x8f, 0xbb, 0x49, 0x27, 0x3f, 0x70, 0x55, 0x68,
	0xae, 0x15, 0x0d, 0x5f, 0xc4, 0x23, 0x4a, 0xb8, 0xb0, 0x5e, 0x4a, 0x11, 0x8b, 0x74, 0xaf, 0xfe,
	0xed, 0xd4, 0x74, 0xba, 0x25, 0x45, 0x83, 0x3c, 0xf5, 0x4d, 0xb0, 0x78, 0x07, 0x91, 0xfe, 0x70,
	0xc5, 0x59, 0x2c, 0xd2, 0x73, 0x15, 0x1c, 0xde, 0xc3, 0xbe, 0x31, 0xa5, 0x6e, 0x8a, 0xaa, 0x25,
	0xb9, 0x73, 0x7f, 0x96, 0x20, 0xf9, 0x15, 0x70, 0xed, 0xc9, 0xdc, 0x9b, 0x8e, 0x09, 0x0f, 0x70,
	0x69, 0x83, 0x0e, 0xec, 0xd9, 0x2f, 0x70, 0xde, 0xc2, 0x79, 0x86, 0xf3, 0x06, 0xce, 0x98, 0x01,
	0x3a, 0xd6, 0x6b, 0xf7, 0x9e, 0x93, 0xfd, 0x26, 0xbb, 0xba, 0xe2, 0x48, 0xf3, 0xf4, 0xe2, 0x77,
	0x98, 0x92, 0xaa, 0x24, 0x7c, 0x84, 0x28, 0x27, 0x6d, 0xcb, 0x4f, 0xbc, 0xc9, 0xdc, 0x66, 0xab,
	0x91, 0x0e, 0xb8, 0x8e, 0xfc, 0x85, 0xc9, 0xc9, 0x5b, 0xe4, 0x66, 0x7d, 0xfe, 0x0b, 0x00, 0x00,
	0xff, 0xff, 0x58, 0xf6, 0xd1, 0xb9, 0x6f, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// TaskServiceClient is the client API for TaskService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type TaskServiceClient interface {
	Search(ctx context.Context, in *TaskRequest, opts ...grpc.CallOption) (*TaskResponse, error)
}

type taskServiceClient struct {
	cc *grpc.ClientConn
}

func NewTaskServiceClient(cc *grpc.ClientConn) TaskServiceClient {
	return &taskServiceClient{cc}
}

func (c *taskServiceClient) Search(ctx context.Context, in *TaskRequest, opts ...grpc.CallOption) (*TaskResponse, error) {
	out := new(TaskResponse)
	err := c.cc.Invoke(ctx, "/task.TaskService/Search", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TaskServiceServer is the server API for TaskService service.
type TaskServiceServer interface {
	Search(context.Context, *TaskRequest) (*TaskResponse, error)
}

// UnimplementedTaskServiceServer can be embedded to have forward compatible implementations.
type UnimplementedTaskServiceServer struct {
}

func (*UnimplementedTaskServiceServer) Search(ctx context.Context, req *TaskRequest) (*TaskResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Search not implemented")
}

func RegisterTaskServiceServer(s *grpc.Server, srv TaskServiceServer) {
	s.RegisterService(&_TaskService_serviceDesc, srv)
}

func _TaskService_Search_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TaskRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TaskServiceServer).Search(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/task.TaskService/Search",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaskServiceServer).Search(ctx, req.(*TaskRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _TaskService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "task.TaskService",
	HandlerType: (*TaskServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Search",
			Handler:    _TaskService_Search_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/task/task.proto",
}
